name = "Serif"
license = "MIT"
licenselink = "https://github.com/sunrise-bay-area/hugo-sunrise-serif-theme/blob/master/LICENSE"
description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
homepage = "https://github.com/sunrise-bay-area/hugo-sunrise-serif-theme"
tags = ["responsive","minimal","clean","business","company","bootstrap","zerostatic","personal","google analytics"]
features = ["services","team","about","contact"]

